module.exports = {
  en: {
    pageTitle: 'OTP Data Entry',
    placesTitle: 'Places',
    placesView: 'View',
    placesEdit: 'Edit',
    placesImage: 'Place Image',
    placeName: 'Name',
    placeDescription: 'Description',
    placeAddress: 'Address',
    placeHours: 'Opening Hours',
    placeLocation: 'Location',
    placeImage: 'Image',
    placeWebsite: 'Website',
    placePhone: 'Phone',
    placeEmail: 'Email',
    placeAccessibility: 'Accessibility Options',
    placeCategories: 'Categories',
    formOwnerId: 'Owner ID',
    formImageUrl: 'Image URL',
    formSubmit: 'Submit',
    brailleMenu: 'Braille Menu',
    wheelchairFriendly: 'Wheelchair Friendly',
    restaurant: 'Restaurant',
    cafe: 'Café'
  },
  ar: {
    pageTitle: 'إدخال البيانات',
    placesTitle: 'أماكن',
    placesView: 'إعرض',
    placesEdit: 'حرر',
    placesImage: 'صورة المكان',
    placeName: 'الإسم',
    placeDescription: 'الوصف',
    placeAddress: 'العنوان',
    placeHours: 'ساعات العمل',
    placeLocation: 'الموقع على الخارطة',
    placeImage: 'صورة',
    placeWebsite: 'الموقع',
    placePhone: 'الهاتف',
    placeEmail: 'البريد الالكتروني',
    placeAccessibility: 'إمكانيات سهولة الوصول',
    placeCategories: 'فئات',
    formOwnerId: 'هوية صاحب المكان',
    formImageUrl: 'صورة',
    formSubmit: 'إعرض',
    brailleMenu: 'قائمة بلغة بريل',
    wheelchairFriendly: 'كرسي نقّال',
    restaurant: 'مطعم',
    cafe: 'مقهى'
  }
};
