module.exports = {
  en: {
    pageTitle: 'OTP Data Entry',
    homePage: 'Home Page',
    english: 'English',
    arabic: 'Arabic',
    error: 'Error',
    serverError: 'Server error',
    badRequest: 'Bad Request',
    notFound: 'Page not found',
    backList: 'Back to list',
    view: 'View',
    edit: 'Edit',
    add: 'Add',
    delete: 'Delete',
    image: 'Image',
    name: 'Name',
    description: 'Description',
    noLocation: 'No Location available',
    accessibilityOptions: 'Accessibility Options',
    categories: 'Categories',
    formInfo:
      '*indicates a required field in at least one of English or Arabic',
    required: 'Required field',
    selectPlace: 'Select place',
    // places
    placesTitle: 'Places',
    placeAddress: 'Address',
    placeHours: 'Opening Hours',
    placeLocation: 'Location',
    // placeImage: 'Image',
    placeWebsite: 'Website',
    viewWebsite: 'Visit their website',
    placePhone: 'Phone',
    placeEmail: 'Email',
    // events
    eventsTitle: 'Events',
    eventsName: 'Name',
    eventsPlace: 'Place',
    eventsPlaceDes: 'Place description',
    eventsCost: 'Cost',
    costNotAvailable: 'Cost not available',
    eventStart: 'Start time',
    eventEnd: 'End time',
    formOwnerId: 'Owner ID',
    formImage: 'Image',
    formImageUrl: 'Image-URL',
    formSubmit: 'Submit',
    // Accessibility options
    audioRecordings: 'Audio recordings',
    brailleMenu: 'Braille',
    bigFonts: 'Big fonts',
    carer: 'Carer',
    guideDog: 'Place for guide dog',
    smsMessaging: 'SMS messaging',
    signLang: 'Sign language',
    goodLighting: 'Good lighting',
    wheelchairFriendly: 'Wheelchair access',
    disabledParking: 'Disabled parking',
    disabledToilet: 'Disabled toilet',
    // Place categories
    cafe: 'Cafe',
    musicVenue: 'Music venue',
    religiousSite: 'Religious site',
    restaurant: 'Food and Drink',
    education: 'Education',
    retail: 'Retail',
    sport: 'Sport',
    municipal: 'Municipal',
    healthcare: 'Healthcare',
    // Event categories
    competition: 'Competition',
    conference: 'Conference',
    culture: 'Culture',
    dining: 'Dining',
    educational: 'Educational',
    launch: 'Launch',
    music: 'Music',
    miscellaneous: 'Miscellaneous',
    party: 'Party',
    sportEvent: 'Sport',
    wedding: 'Wedding',
  },
  ar: {
    pageTitle: 'إدخال البيانات',
    homePage: 'الصفحة الرئيسية',
    english: 'الانجليزية',
    arabic: 'العربية',
    error: 'خطأ',
    serverError: 'خطأ في الخادم',
    badRequest: 'خطأ في ارسال الطلب',
    notFound: 'لم يتم ايجاد الصفحة',
    backList: 'عودة الى القائمة',
    view: 'عرض',
    edit: 'تعديل',
    add: 'اضافة',
    delete: 'ازالة',
    image: 'صورة',
    name: 'الاسم',
    description: 'الوصف',
    noLocation: 'لا يوجد مكان',
    accessibilityOptions: 'امكانيات سهولة الوصول',
    categories: 'فئات',
    formInfo:
      '* مطلوب التعبئة على الاقل في واحدة من اللغتين العربية او الانجليزية',
    required: ' مطلوب التعبئة',
    selectPlace: 'اختر مكان الحدث',
    // places
    placesTitle: 'أماكن',
    placesView: 'إعرض',
    placesEdit: 'حرر',
    placesAdd: 'اضافة مكان',
    placesDelete: 'ازالة المكان',
    placesImage: 'صورة المكان',
    placeName: 'الإسم',
    placeDescription: 'الوصف',
    placeAddress: 'العنوان',
    placeHours: 'ساعات العمل',
    placeLocation: 'الموقع على الخارطة',
    placeImage: 'صورة',
    placeWebsite: 'الموقع',
    viewWebsite: 'ادخل الى الموقع',
    placePhone: 'الهاتف',
    placeEmail: 'البريد الالكتروني',
    placeAccessibility: 'إمكانيات سهولة الوصول',
    // events
    eventsTitle: 'احداث',
    eventsName: 'اسم الحدث',
    eventsPlace: 'المكان',
    eventsPlaceDes: 'عن المكان',
    eventsCost: 'السعر',
    costNotAvailable: 'السعر غير موجود',
    eventStart: 'وقت البدء',
    eventEnd: 'وقت النهاية',
    formOwnerId: 'هوية صاحب المكان',
    formImage: 'صورة',
    formImageUrl: 'رابط الصورة',
    formSubmit: 'إعرض',
    // Accessibility options
    audioRecordings: 'خدمات صوتية',
    brailleMenu: 'قائمة بلغة بريل',
    bigFonts: 'خط كبير',
    carer: 'مقدم رعاية',
    guideDog: 'مكان لكلب المرافق للمكفوفين',
    smsMessaging: 'خدمة الرسائل',
    signLang: 'لغة الاشارات',
    goodLighting: 'اضاءة مناسبة ',
    wheelchairFriendly: 'كرسي نقّال',
    disabledParking: 'موقف لذوي الاحتياجات الخاصة',
    disabledToilet: 'حمام ذوي الاحتياجات الخاصة',
    // Place categories
    cafe: 'مقهى',
    musicVenue: 'مكان موسيقي',
    religiousSite: 'مواقع دينية',
    restaurant: 'مأكولات ومشروبات',
    education: 'تربية وتعليم',
    retail: 'بيع وتجارة',
    sport: 'ترفيه ورياضة',
    municipal: 'مكاتب حكومية وبلدية',
    healthcare: 'صحة',
    // Event categories
    competetion: 'مسابقة',
    conference: 'مؤتمر',
    culture: 'حضارة',
    dining: 'طعام',
    educational: 'ثقافي',
    launch: 'افتتاح',
    music: 'موسيقى',
    miscellaneous: 'متنوع',
    party: 'حفل',
    sportEvent: 'رياضة',
    wedding: 'عرس',
  },
};
