module.exports = {
  en: {
    pageTitle: 'OTP Data Entry',
    placesTitle: 'Places',
    placesView: 'View',
    placesEdit: 'Edit',
    placesAdd: 'Add',
    placesImage: 'Place Image',
    placeName: 'Name',
    placeDescription: 'Description',
    placeAddress: 'Address',
    placeHours: 'Opening Hours',
    placeLocation: 'Location',
    placeImage: 'Image',
    placeWebsite: 'Website',
    placePhone: 'Phone',
    placeEmail: 'Email',
    placeAccessibility: 'Accessibility Options',
    placeCategories: 'Categories',
    formOwnerId: 'Owner ID',
    formImageUrl: 'Image URL',
    formSubmit: 'Submit',
    // Accessibility options
    audioRecordings: 'Audio recordings',
    brailleMenu: 'Braille',
    bigFonts: 'Big fonts',
    carer: 'Carer',
    guideDog: 'Place for guide dog',
    smsMessaging: 'SMS messaging',
    signLang: 'Sign language',
    goodLighting: 'Good lighting',
    wheelchairFriendly: 'WheelChair access',
    disabledParking: 'Disabled parking',
    disabledToilet: 'Disabled toilet',
    // Place categories
    cafe: 'cafe',
    musicVenue: 'music venue',
    religiousSite: 'religious site',
    restaurant: 'food and drink',
    education: 'education',
    retail: 'retail',
    sport: 'sport',
    municipal: 'municipal',
    healthcare: 'healthcare'
  },
  ar: {
    pageTitle: 'إدخال البيانات',
    placesTitle: 'أماكن',
    placesView: 'إعرض',
    placesEdit: 'حرر',
    placesAdd: 'اضافة مكان',
    placesImage: 'صورة المكان',
    placeName: 'الإسم',
    placeDescription: 'الوصف',
    placeAddress: 'العنوان',
    placeHours: 'ساعات العمل',
    placeLocation: 'الموقع على الخارطة',
    placeImage: 'صورة',
    placeWebsite: 'الموقع',
    placePhone: 'الهاتف',
    placeEmail: 'البريد الالكتروني',
    placeAccessibility: 'إمكانيات سهولة الوصول',
    placeCategories: 'فئات',
    formOwnerId: 'هوية صاحب المكان',
    formImageUrl: 'صورة',
    formSubmit: 'إعرض',
    // Accessibility options
    audioRecordings: 'خدمات صوتية',
    brailleMenu: 'قائمة بلغة بريل',
    bigFonts: 'خط كبير',
    carer: 'مقدم رعاية',
    guideDog: 'مكان لكلب المرافق للمكفوفين',
    smsMessaging: 'خدمة الرسائل',
    signLang: 'لغة الاشارات',
    goodLighting: 'اضاءة مناسبة ',
    wheelchairFriendly: 'كرسي نقّال',
    disabledParking: 'موقف لذوي الاحتياجات الخاصة',
    disabledToilet: 'حمام ذوي الاحتياجات الخاصة',
    // Place categories
    cafe: 'مقهى',
    musicVenue: 'مكان موسيقي',
    religiousSite: 'مواقع دينية',
    restaurant: 'مأكولات ومشروبات',
    education: 'تربية وتعليم',
    retail: 'بيع وتجارة',
    sport: 'ترفيه ورياضة',
    municipal: 'مكاتب حكومية وبلدية',
    healthcare: 'صحة'

  }
};
